### ISSUE TITLE
ログの処理中に例外が発生することがある

### ISSUE THREAD

**Issue by rioil** [rioil/VRChatLifelog#8]
出力されたログ

```
2022-12-01 18:37:27.4583 [Info] Reading C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_07-25-12.txt... 
2022-12-01 18:37:27.7878 [Info] Watching file changed to C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_2022-12-01_18-01-39.txt 
2022-12-01 18:37:27.7878 [Info] Starting log directory watching... 
2022-12-01 18:37:27.7878 [Info] Log directory watching started 
2022-12-01 18:37:27.9018 [Debug] Hosting started 
2022-12-01 22:26:31.1522 [Info] New log file created : C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_2022-12-01_22-26-31.txt 
2022-12-01 22:26:31.1522 [Info] Watching file changed to C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_2022-12-01_22-26-31.txt 
2022-12-01 22:26:31.1522 [Info] New log file created : C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_2022-12-01_22-26-31.txt 
2022-12-01 22:26:31.1522 [Info] Watching file changed to C:\Users\rio\AppData\LocalLow\VRChat\VRChat\output_log_2022-12-01_22-26-31.txt 
2022-12-01 22:46:35.3401 [Error] CurrentDomain_UnhandledException System.NullReferenceException: Object reference not set to an instance of an object.
   at VRChatLogWathcer.Models.LogWathcerService.<>c__DisplayClass27_0.<<ChangeWatchingFile>b__0>d.MoveNext() in D:\rio\dev\C#\VRChatLifelog\VRChatLogWathcer\Models\LogWathcerService.cs:line 320
--- End of stack trace from previous location ---
   at VRChatLogWathcer.Models.LogWathcerService.StopLogFileWatching() in D:\rio\dev\C#\VRChatLifelog\VRChatLogWathcer\Models\LogWathcerService.cs:line 374
   at VRChatLogWathcer.Models.LogWathcerService.ChangeWatchingFile(String filePath) in D:\rio\dev\C#\VRChatLifelog\VRChatLogWathcer\Models\LogWathcerService.cs:line 317
   at VRChatLogWathcer.Models.LogWathcerService.OnFileCreated(String fileFullPath) in D:\rio\dev\C#\VRChatLifelog\VRChatLogWathcer\Models\LogWathcerService.cs:line 186
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by rioil** [comment]
1年以上発生していないため，おそらく修正済み．
